name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Hub Login
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Rpi.Docker image
      run: docker build . --file Rpi.Dockerfile --tag ${{secrets.DOCKER_USER}}/myfastapiserver:$(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/myfastapiserver
